"""change email into string

Revision ID: 45ee6450d961
Revises: 
Create Date: 2025-08-08 06:09:16.232184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45ee6450d961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_key', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('valid_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'4'"))

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Text(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('chat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('question',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_general_ci'),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('status_report',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('opinion',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.alter_column('monthly_active',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('token_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_input_tokens',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_output_tokens',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cost_to_date',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('chat_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('product_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('search',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('products',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('product_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('wallet_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('valid_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('access_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('payment_mothod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mothod', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('amount',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('access_key',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True)
        batch_op.alter_column('valid_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('wallet_address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('userid',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)

    with op.batch_alter_table('product_history', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('products',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=True)
        batch_op.alter_column('search',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('device_id',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('chat_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cost_to_date',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_output_tokens',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_input_tokens',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('token_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('monthly_active',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('opinion',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('status_report',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=True)
        batch_op.drop_column('mode')

    with op.batch_alter_table('access_key', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'4'"))
        batch_op.alter_column('valid_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    # ### end Alembic commands ###
